on:
    push:
        branches:
            - main
    workflow_dispatch:
    schedule:
      - cron: '0 0 * * WED'
  
name: Render README
  
jobs:
    render-rmarkdown:
        runs-on: ubuntu-latest
        env:
            GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/checkout@v4
              with:
                repository: drmowinckels/drmowinckels.github.io
                path: website

            - name: Install cURL Headers
              run: |
                sudo apt-get update
                sudo apt-get install libcurl4-openssl-dev

            - uses: r-lib/actions/setup-r@v2
            - uses: r-lib/actions/setup-pandoc@v2
            - uses: r-lib/actions/setup-renv@v2

            - name: Render README
              run:  rmarkdown::render("README.Rmd", "github_document")
              shell: Rscript {0}
            - name: Commit results
              run: |
                git config --local user.email "actions@github.com"
                git config --local user.name "GitHub Actions"
                git commit README.md README-files/ \
                    -m 'Re-build README.Rmd' || echo "No changes to commit"
                git push origin || echo "No changes to commit"
